#!/usr/bin/env python3
"""Start saved semantic-map loading and semantic Nav2 goal resolution."""
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description() -> LaunchDescription:
    arguments = [
        DeclareLaunchArgument(
            "semantic_map_path",
            default_value="/tmp/semantic_objects.json",
            description="Saved JSON generated by my_work_pkg",
        ),
        DeclareLaunchArgument(
            "excluded_labels",
            default_value="['person']",
            description="Dynamic labels excluded from the saved static map",
        ),
        DeclareLaunchArgument("use_sim_time", default_value="false"),
        DeclareLaunchArgument("map_topic", default_value="/map"),
        DeclareLaunchArgument("base_frame", default_value="base_link"),
        DeclareLaunchArgument("navigate_action", default_value="/navigate_to_pose"),
        DeclareLaunchArgument("standoff_m", default_value="0.7"),
        DeclareLaunchArgument("robot_clearance_m", default_value="0.35"),
        DeclareLaunchArgument("occupied_threshold", default_value="50"),
        DeclareLaunchArgument("reject_unknown", default_value="true"),
        DeclareLaunchArgument("approach_samples", default_value="32"),
    ]

    loader = Node(
        package="semantic_navigation_pkg",
        executable="semantic_map_loader_node",
        name="semantic_map_loader_node",
        output="screen",
        parameters=[{
            "semantic_map_path": LaunchConfiguration("semantic_map_path"),
            "excluded_labels": LaunchConfiguration("excluded_labels"),
            "output_topic": "/semantic_map/objects",
            "use_sim_time": LaunchConfiguration("use_sim_time"),
        }],
    )
    resolver = Node(
        package="semantic_navigation_pkg",
        executable="semantic_goal_resolver_node",
        name="semantic_goal_resolver_node",
        output="screen",
        parameters=[{
            "semantic_objects_topic": "/semantic_map/objects",
            "map_topic": LaunchConfiguration("map_topic"),
            "use_sim_time": LaunchConfiguration("use_sim_time"),
            "base_frame": LaunchConfiguration("base_frame"),
            "navigate_action": LaunchConfiguration("navigate_action"),
            "standoff_m": LaunchConfiguration("standoff_m"),
            "robot_clearance_m": LaunchConfiguration("robot_clearance_m"),
            "occupied_threshold": LaunchConfiguration("occupied_threshold"),
            "reject_unknown": LaunchConfiguration("reject_unknown"),
            "approach_samples": LaunchConfiguration("approach_samples"),
        }],
    )

    return LaunchDescription([*arguments, loader, resolver])

